### ISSUE TITLE
Please add JUG Milano meetings

### ISSUE THREAD

**Issue by flerro** [kandros/milano.dev-data#26]
Please add JUG Milano (monthly) meetings, using custom source: http://www.jugmilano.it/meetings 

You may navigate to details for next event using the `href` of `#main > section > ul:nth-child(3) > li > a`

On event detail page you will find:

- event title:  `#main > div:nth-child(2)`
- event date: `#main > hgroup > p > span`
- event location (a bit tricky): in text following event title

**Comment by kandros** [comment]
Thanks @flerro for the details

A custom scraper is already present for JUG (last event was visible on milano.dev)

(We need to make it easier to show when communities outside of meetup/eventbrite and not shown in this repo are already been processed 😁)

**Comment by kandros** [comment]
@all-contributors please add @flerro for content
