### ISSUE TITLE
Add Coding Gym

### ISSUE THREAD

**Issue by Loghorn** [kandros/milano.dev-data#6]
The Eventbrite link is https://www.eventbrite.it/o/coding-gym-16859146671 but it lists all the Coding Gym events, not just the one in Milan.
If you prefer only Milan dates, you can scrap here: https://coding-gym.org/locations/milan/

Thank you

**Comment by kandros** [comment]
Thanks! I've added a custom scraper

**Comment by kandros** [comment]
@all-contributors please add @Loghorn for content
